### ISSUE TITLE
FV: Social Recovery Module Setup and Revocation

### ISSUE THREAD

**Issue by remedcu** [5afe/CandideWalletContracts#12]
## Intention

> An owner through Safe should be able to add or remove the recovery module anytime. (Guard is disabled, as it can prevent modules from being added/removed)

## Description

As a Safe Smart Account Wallet owner of a safe with n/m owner structure, the owner should be able to:
- add Recovery Module
- remove Recovery Module
 
at any time the owner intends, with the required amount of signature for the safe wallet (Here the assumption is that all the safe owners unanimously support the actions mentioned above)

## Expected Outcome

Rules which verify the actions mentioned above are true at any point in time.

**Comment by nlordell** [comment]
This _should_ be covered by Safe FV, and not needed in the module. For now, we keep the issue around in case we change our mind, but this is likely not needed.
