### ISSUE TITLE
FV: Delay period should be complete for the finalization process

### ISSUE THREAD

**Issue by remedcu** [5afe/CandideWalletContracts#14]
## Intention

> There is no way to speed up the recovery delay process, it always has to pass the delay period for the finalize recovery to be called successfully.

## Description

Once the recovery is initiated by the guardian, there is a delay period (`immutable` per module) which needs to be completed, only after which the finalization of recovery can be done (by anyone).

It should not be possible for anyone (including the guardian), to call the finalization process before the delay period is complete. Two things can be considered (after initialization):
- If the delay period is not completed, the finalization step should always revert.
- If the delay period is complete, the finalization step should always execute (unless front-run by a cancellation from the owner)

## Expected Outcome

Rule/Invariant to verify that the delay period should always be complete to finalize the recovery process.

**Comment by nlordell** [comment]
Completed in https://github.com/5afe/CandideWalletContracts/pull/35
