### ISSUE TITLE
FV: Initiation of a Recovery by Guardian Signatures

### ISSUE THREAD

**Issue by remedcu** [5afe/CandideWalletContracts#17]
Initiation of recovery by aggregating the signatures to reach the threshold amount of guardians.

**Comment by mmv08** [comment]
Adding more details about the issue from @remedcu from slack:
> This rule should verify that using multiConfirmRecovery(...) an address (does not "need" to be a guardian for this one) can call with valid signatures from guardians and initiate the recovery.
If you want to go an extra step, can also check if the execution of recovery is happening correctly or not.
P.S. On a quick look, this line could be useless: [https://github.com/5afe/CandideWalletContracts/blob/870f82d3c4d286b3fd9241c6479c94[…]3fc6/contracts/modules/social_recovery/SocialRecoveryModule.sol](https://github.com/5afe/CandideWalletContracts/blob/870f82d3c4d286b3fd9241c6479c9472d7d73fc6/contracts/modules/social_recovery/SocialRecoveryModule.sol#L188) as even if we have 3 same signature, going through them will just overwrite the mapping. Same reason can be said about ordering of the signer's.
