### ISSUE TITLE
FV: Initiation of a Recovery by Guardian

### ISSUE THREAD

**Issue by remedcu** [5afe/CandideWalletContracts#6]
## Intention

> Only a guardian should be allowed to initiate a recovery.

## Description

The Recovery Module's, recovery initiation is done by the Guardian, added by the Safe Wallet Owners. No other user should be able to initiate the recovery process. There are two functions using which we can initiate the recovery based on the number of participants involved:
- Initiation by a guardian (with 1/m or n/m guardian threshold)

~- Initiation by a single guardian by aggregating the signatures to reach the threshold amount of guardians.~

## Expected Outcome

Rules/Invariants to verify mainly two things:
- Only guardian/s can initiate recovery.
- Anyone, other than a guardian, should not be able to initiate a recovery.

Both of the above can be achieved in CVL as:
> if recovery was initiated, then `msg.sender` is a guardian

**Comment by nlordell** [comment]
In CVL this can be expressed as "if recovery was initiated, then `msg.sender` is a guardian". This might be a more powerful rule that covers both these cases.
